---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2021
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: Check End-to-End execution
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 'master'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: ./scripts/install.sh
      - name: Deploy GW-Tester services
        run: |
          source /etc/profile.d/path.sh
          IMAGE_VERSION=dev make build deploy
      
          # Wait for services
          attempt_counter=0
          max_attempts=30
          until [ "$(sudo docker ps --filter "name=deployments_*_1*" --format "{{.Names}}" | wc -l)" -gt "6" ]; do
              if [ ${attempt_counter} -eq ${max_attempts} ];then
                  echo "Max attempts reached"
                  sudo docker info
                  sudo docker ps -a
                  make logs

                  exit 1
              fi
              attempt_counter=$((attempt_counter+1))
              sleep 10
          done
          sleep 10 # Wait for few client requests
      - name: Validate GW-Tester communication
        run: sudo ./scripts/check.sh
